#!/usr/bin/env bash

set -eufo pipefail

if [ "${1-}" = --second-stage ]; then
	shift
	mount -t tmpfs -o size=4G tmpfs /tmp
	"$@"
	if [ -d /builder/.build ]; then
		chown "$(stat -c "%u:%g" /builder/.build)" -R /builder/.build
	fi
else
	unshare --map-root-user --map-users auto --map-groups auto --mount "$0" --second-stage "$@"
fi
