#!/usr/bin/env bash

set -Eeufo pipefail

veritytab=
cert_base="/builder/cert/secureboot.db"
timestamp=0
secureboot="true"
dracut_include=
tpm2=

while [ $# -gt 0 ]; do
	case "$1" in
		-r|--rootfs)
			rootfs="$2"
			shift 2
			;;
		-c|--cmdline)
			cmdline="$2"
			shift 2
			;;
		-v|--veritytab)
			veritytab="$2"
			shift 2
			;;
		--cert)
			cert_base="${2%.crt}"
			if [ -n "$cert_base" ] && [ "$cert_base.crt" != "$2" ]; then
				echo "cert file must end in .crt" >&2
				exit 1
			fi
			shift 2
			;;
		-t|--timestamp)
			timestamp="$2"
			shift 2
			;;
		-s|--secureboot)
			secureboot="$2"
			shift 2
			;;
		--tpm2)
			tpm2="tpm2-tss"
			shift
			;;
		-i|--include)
			dracut_include="$2"
			shift 2
			;;
		*)
			break
			;;
	esac
done

initrd="$(mktemp)"
unified_image="$(mktemp)"
unified_image_signed="$(mktemp)"

[ ! -e "$rootfs$initrd" ]
touch "$rootfs$initrd"
mount --bind "$initrd" "$rootfs$initrd"
[ ! -e "$rootfs$dracut_include" ]
mkdir -p "$rootfs$dracut_include"
mount --bind "$dracut_include" "$rootfs$dracut_include"
[ ! -s "$rootfs/etc/veritytab" ]
touch "$rootfs/etc/veritytab"
[ -z "$veritytab" ] || mount --bind "$veritytab" "$rootfs/etc/veritytab"
[ -d "$rootfs/proc" ]
mount --rbind /proc "$rootfs/proc"
[ -d "$rootfs/dev" ]
mount --rbind /dev "$rootfs/dev"

kernel_file=$(find "$rootfs/boot/" -name 'vmlinuz-*')
kernel_version="${kernel_file#*-}"

unshare --user --map-root-user --mount -- bash -c 'mount -t tmpfs -o size='"$TEMPFS_SIZE"' tmpfs '"$rootfs/var/tmp"' && mount -t tmpfs -o size='"$TEMPFS_SIZE"' tmpfs /sys && mount --bind /usr/bin/false /usr/bin/systemd-detect-virt && "$@"' -- \
chroot "$rootfs" env dracut \
	--no-hostonly \
	--force \
	--kver "$kernel_version" \
	--modules "bash dash systemd systemd-initrd systemd-veritysetup systemd-repart kernel-modules kernel-modules-extra terminfo udev-rules dracut-systemd base fs-lib shutdown crypt $tpm2" \
	--install "/etc/veritytab cryptsetup head mkfs.ext4 systemd-escape lsblk" \
	--include "$dracut_include" "/" \
	--reproducible \
	"$initrd"

umount -l "$rootfs/dev"
umount -l "$rootfs/proc"
umount "$rootfs$initrd"
rm "$rootfs$initrd"
umount "$rootfs$dracut_include"
rmdir "$rootfs$dracut_include"
umount "$rootfs/etc/veritytab"
rm "$rootfs/etc/veritytab"

case "$BUILDER_ARCH" in
	amd64)
		uefi_arch=X64
		gnu_arch=x86_64
		;;
	arm64)
		uefi_arch=AA64
		gnu_arch=aarch64
		;;
esac

# create unified image
/usr/lib/systemd/ukify build \
	--stub "$rootfs/usr/lib/systemd/boot/efi/linux$(tr '[:upper:]' '[:lower:]' <<< "$uefi_arch").efi.stub" \
	--linux "$kernel_file" \
	--initrd "$initrd" \
	--cmdline "$cmdline" \
	--output "$unified_image"

efi_dir="$(mktemp -d)"
mkdir -p "$efi_dir/EFI/BOOT/"

if [[ "$secureboot" = "true" ]]; then
	if [ -f "$cert_base.key" ]; then
		key_params=(--key "$cert_base.key")
	elif [ -f "$cert_base.arn" ]; then
		PKCS11_MODULE_PATH="/usr/lib/$(uname -m)-linux-gnu/pkcs11/aws_kms_pkcs11.so"
		export PKCS11_MODULE_PATH
		key_params=(--engine pkcs11 --key "pkcs11:token=$(basename "$(cat "$cert_base.arn")" | cut -c -32)")
	else
		echo "neither $cert_base.key nor $cert_base.arn exists, but at least one is required" >&2
		exit 1
	fi

	# sign unified image
	datefudge -s "@$timestamp" sbsign --cert "$cert_base.crt" "${key_params[@]}" --output "$unified_image_signed" "$unified_image"
	rm "$unified_image"

	ls -lah "$unified_image_signed"

	mv "$unified_image_signed" "$efi_dir/EFI/BOOT/BOOT$uefi_arch.EFI"
else
	mv "$unified_image" "$efi_dir/EFI/BOOT/BOOT$uefi_arch.EFI"
fi

while read -r partition_file; do
	if [[ "$BUILDER_ARCH" = "amd64" ]] && [[ ! "$secureboot" = "true" ]]; then
	# add roothash to legacy boot kernel cmdline
		syslinux=$(mktemp)
		mcopy -i "$partition_file" -p ::/syslinux/syslinux.cfg "$syslinux"
		sed -i "s/root=[^ ]*/$(echo "$cmdline" | cut -d ' ' -f 1)/g" "$syslinux"
		mcopy -i "$partition_file" -po "$syslinux" ::/syslinux/syslinux.cfg
	# copy initrd.img for legacy boot when secureboot feature is not enabled
		datefudge -s "@$timestamp" mcopy -i "$partition_file" -o -p "$initrd" "::/Default/${kernel_version}/initrd.img-${kernel_version}"
	fi
	if [[ ! "$secureboot" = "true" ]]; then
	# clean up EFI directory
		mdeltree -i "$partition_file" ::/EFI
	fi
	# copy unified image to uefi partition
	datefudge -s "@$timestamp" mcopy -i "$partition_file" -s -p "$efi_dir/EFI" "::/EFI"
done

rm "$initrd"
rm -rf "$efi_dir"
