#!/usr/bin/env bash

set -efo pipefail

target="$1"
shift

echo -n | cat "${@/%/.log}" > "$target.log"

while IFS= read -r line; do
	date="$(date -u '+%Y-%m-%d %H:%M:%S')"

	if [ "${CI}" == "true" ]; then
		printf '[%s] %s\n' "$target" "$line"
	else
		printf '[%s %s] %s\n' "$target" "$date" "$line"
	fi

	printf '[%s] %s\n' "$date" "$line" >> "$target.log"
done
