#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

cname="$1"

IFS=',' read -r -a features < <(./parse_features --feature-dir features --cname "$cname" features)

artifacts=(".build/$cname-$COMMIT.tar")

for feature in "${features[@]}"; do
	for i in "features/$feature/"{image,convert}.*; do
		extension="$(grep -E -o '(\.[a-z][a-zA-Z0-9\-_]*)*$' <<< "$i")"
		artifacts+=(".build/$cname-$COMMIT$extension")
	done
done

if [ "${#artifacts[@]}" = 0 ] && [ -n "$(./parse_features --feature-dir "features" --cname "$cname" platforms)" ]; then
	artifacts+=(".build/$cname-$COMMIT.raw")
fi

echo "${artifacts[@]}"
